development:
  secret_key_base: e328070fe082224bc328b984566ac572e2810cf0919c36528619a8d6dad0a5688dcc526e4fae3fba22929bb855fdea12a60f85a3bc7c46dee5e79f4fa21e3ad6
  fb_APP_ID: <%= ENV["FB_APP_ID"] %>
  fb_APP_SECRET: <%= ENV["FB_APP_SECRET"] %>

test:
  secret_key_base: f6b51ca8cae4dc972cc9bbf5211cac4ff1fd33718f4bddd0d771d38d97b4f4cb8c598f7f33cf493e8ee6d0ec71f23e1ef088f97a9103d85c944dc20f949fe772
  fb_APP_ID: <%= ENV["FB_APP_ID"] %>
  fb_APP_SECRET: <%= ENV["FB_APP_SECRET"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_APP_ID: <%= ENV["FB_APP_ID"] %>
  fb_APP_SECRET: <%= ENV["FB_APP_SECRET"] %>